[package]
name = "simple-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
rand = "0.8.5"
random_name_generator = "0.3.6"
termion = "2.0.3"
